CREATE TABLE DOWNLOAD_LOG(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DATE_DOWNLOADED TEXT,
	USER TEXT,
	SUB_REDDIT TEXT,
	URL TEXT,
	PERMALINK TEXT,
	TITLE TEXT,
	IS_ALBUM TEXT
);

CREATE VIEW IMAGES_BY_SUBREDDIT AS
SELECT 	COUNT(*) AS COUNT, 
		SUB_REDDIT 
FROM 	DOWNLOAD_LOG 
GROUP BY 
		SUB_REDDIT
ORDER BY
		COUNT DESC;