CREATE TABLE DOWNLOAD_LOG(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DATE_DOWNLOADED TEXT,
	SAVED_USER TEXT,
	POSTED_BY TEXT,
	SUB_REDDIT TEXT,
	URL TEXT,
	ALBUM_URL TEXT,
	FILE_NAME TEXT,
	PERMALINK TEXT,
	TITLE TEXT,
	IS_ALBUM TEXT,
	ALBUM_INDEX INT
);

CREATE TABLE JOB_TRACKER(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	START_DATE TEXT,
	END_DATE TEXT
);

CREATE VIEW IMAGES_BY_SUBREDDIT AS
SELECT 	COUNT(*) AS COUNT, 
		SUB_REDDIT 
FROM 	DOWNLOAD_LOG 
GROUP BY 
		SUB_REDDIT
ORDER BY
		COUNT DESC;